
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vboxMain;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView textviewText;

	private global::Gtk.HPaned hpaned3;

	private global::Gtk.HBox hboxBottom;

	private global::Gtk.VBox vboxBottomLeft;

	private global::Gtk.TextView textviewKey;

	private global::Gtk.ScrolledWindow GtkScrolledWindow2;

	private global::Gtk.TextView textviewLog;

	private global::Gtk.VBox vboxBottomRight;

	private global::Gtk.ComboBox cboVoice;

	private global::Gtk.HScale hscaleSpeed;

	private global::Gtk.Button buttonListent;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Zalo Ai Text to Speech");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vboxMain = new global::Gtk.VBox();
		this.vboxMain.Name = "vboxMain";
		this.vboxMain.Spacing = 6;
		// Container child vboxMain.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textviewText = new global::Gtk.TextView();
		this.textviewText.Buffer.Text = global::Mono.Unix.Catalog.GetString("Từ thời thái cổ, nhân loại đối với thế giới quanh mình, thảy những sư" +
				"̣ kỳ dị, chớp loè sấm động, gió dữ mưa to lakjsdhflasdf slkasjdfl aflkas" +
				"djflasdkfjalsdfaslkfdj");
		this.textviewText.CanFocus = true;
		this.textviewText.Name = "textviewText";
		this.textviewText.WrapMode = ((global::Gtk.WrapMode)(2));
		this.textviewText.LeftMargin = 5;
		this.textviewText.RightMargin = 5;
		this.GtkScrolledWindow.Add(this.textviewText);
		this.vboxMain.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.GtkScrolledWindow]));
		w2.Position = 0;
		// Container child vboxMain.Gtk.Box+BoxChild
		this.hpaned3 = new global::Gtk.HPaned();
		this.hpaned3.CanFocus = true;
		this.hpaned3.Name = "hpaned3";
		this.hpaned3.Position = 10;
		// Container child hpaned3.Gtk.Paned+PanedChild
		this.hboxBottom = new global::Gtk.HBox();
		this.hboxBottom.Name = "hboxBottom";
		this.hboxBottom.Spacing = 6;
		// Container child hboxBottom.Gtk.Box+BoxChild
		this.vboxBottomLeft = new global::Gtk.VBox();
		this.vboxBottomLeft.Name = "vboxBottomLeft";
		this.vboxBottomLeft.Spacing = 6;
		// Container child vboxBottomLeft.Gtk.Box+BoxChild
		this.textviewKey = new global::Gtk.TextView();
		this.textviewKey.WidthRequest = 512;
		this.textviewKey.HeightRequest = 14;
		this.textviewKey.CanFocus = true;
		this.textviewKey.Name = "textviewKey";
		this.textviewKey.LeftMargin = 5;
		this.vboxBottomLeft.Add(this.textviewKey);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vboxBottomLeft[this.textviewKey]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Padding = ((uint)(3));
		// Container child vboxBottomLeft.Gtk.Box+BoxChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.textviewLog = new global::Gtk.TextView();
		this.textviewLog.Name = "textviewLog";
		this.textviewLog.Editable = false;
		this.textviewLog.WrapMode = ((global::Gtk.WrapMode)(2));
		this.GtkScrolledWindow2.Add(this.textviewLog);
		this.vboxBottomLeft.Add(this.GtkScrolledWindow2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vboxBottomLeft[this.GtkScrolledWindow2]));
		w5.Position = 1;
		this.hboxBottom.Add(this.vboxBottomLeft);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hboxBottom[this.vboxBottomLeft]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hboxBottom.Gtk.Box+BoxChild
		this.vboxBottomRight = new global::Gtk.VBox();
		this.vboxBottomRight.Name = "vboxBottomRight";
		this.vboxBottomRight.Spacing = 6;
		// Container child vboxBottomRight.Gtk.Box+BoxChild
		this.cboVoice = global::Gtk.ComboBox.NewText();
		this.cboVoice.Name = "cboVoice";
		this.vboxBottomRight.Add(this.cboVoice);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vboxBottomRight[this.cboVoice]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vboxBottomRight.Gtk.Box+BoxChild
		this.hscaleSpeed = new global::Gtk.HScale(null);
		this.hscaleSpeed.CanFocus = true;
		this.hscaleSpeed.Name = "hscaleSpeed";
		this.hscaleSpeed.Adjustment.Lower = 8D;
		this.hscaleSpeed.Adjustment.Upper = 13D;
		this.hscaleSpeed.Adjustment.PageIncrement = 1D;
		this.hscaleSpeed.Adjustment.PageSize = 1D;
		this.hscaleSpeed.Adjustment.StepIncrement = 1D;
		this.hscaleSpeed.Adjustment.Value = 10D;
		this.hscaleSpeed.DrawValue = true;
		this.hscaleSpeed.Digits = 0;
		this.hscaleSpeed.ValuePos = ((global::Gtk.PositionType)(2));
		this.vboxBottomRight.Add(this.hscaleSpeed);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vboxBottomRight[this.hscaleSpeed]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vboxBottomRight.Gtk.Box+BoxChild
		this.buttonListent = new global::Gtk.Button();
		this.buttonListent.CanFocus = true;
		this.buttonListent.Name = "buttonListent";
		this.buttonListent.UseUnderline = true;
		this.buttonListent.Label = global::Mono.Unix.Catalog.GetString("Nghe");
		this.vboxBottomRight.Add(this.buttonListent);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vboxBottomRight[this.buttonListent]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		this.hboxBottom.Add(this.vboxBottomRight);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hboxBottom[this.vboxBottomRight]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		this.hpaned3.Add(this.hboxBottom);
		this.vboxMain.Add(this.hpaned3);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.hpaned3]));
		w12.Position = 1;
		this.Add(this.vboxMain);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 737;
		this.DefaultHeight = 615;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.buttonListent.Clicked += new global::System.EventHandler(this.OnButtonListentClicked);
	}
}
